---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.pnm

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install -g phantomjs-prebuilt
  - npm install -g codeclimate-test-reporter codecov

install:
  - npm install
  - bower install

script:
  - npm test

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - codecov
