version: "2"
services:
  webcat:
    build: ./
    links:
      - identifier:backend
    ports:
      - 80:80
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
    volumes:
      - ./mu/config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./mu/data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.10.1
    links:
      - db:database
    volumes:
      - ./mu/config/resources:/config
    environment:
      BOOT: mu-cl-resources
    ports:
      - "4080:80"
